name: flutter_facebook_auth_web
description: web support for flutter_facebook_auth
version: 3.2.0
homepage: https://github.com/darwin-morocho/flutter-facebook-auth/tree/master/facebook_auth_web
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  js: ^0.6.3
  # flutter_facebook_auth_platform_interface: ^3.2.0
  flutter_facebook_auth_platform_interface:
    git: 
      url: https://github.com/K9i-0/flutter-facebook-auth
      path: flutter_facebook_auth_platform_interface
      ref: support_dataAccessExpirationTime_dev
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      web:
        pluginClass: FlutterFacebookAuthPlugin
        fileName: flutter_facebook_auth_web.dart
